# Generated by Django 5.1.1 on 2024-09-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REMS', '0002_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
